name: Build

# Relevant to events - https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows
on: 
  pull_request:
    types: [opened, reopened, ready_for_review]
    paths:
    - '**.hs'
    - 'Makefile'

strategy:
  matrix:
    runners: [ ubuntu-latest, macos-latest, windows-latest ]

jobs:
  build:
    runs-on: ${{ matrix.runners }}
    steps:
      - name: Pulling git dir..
        uses: actions/checkout@v2
      - name: Building..
        run: make build